"""Private local storage for chat attachments.

Attachment keys are generated by the server and never contain client paths.
The storage directory is intentionally not mounted as a static web directory.
"""

import codecs
import os
import re
import uuid
from pathlib import Path

from fastapi import UploadFile


MAX_ATTACHMENT_BYTES = 25 * 1024 * 1024
CHUNK_SIZE = 64 * 1024

# Canonical MIME type and message type for each accepted extension.
ALLOWED_TYPES = {
    ".jpg": ("image/jpeg", "image"),
    ".jpeg": ("image/jpeg", "image"),
    ".png": ("image/png", "image"),
    ".webp": ("image/webp", "image"),
    ".pdf": ("application/pdf", "file"),
    ".txt": ("text/plain", "file"),
    ".doc": ("application/msword", "file"),
    ".docx": (
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "file",
    ),
    ".xls": ("application/vnd.ms-excel", "file"),
    ".xlsx": (
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        "file",
    ),
    ".zip": ("application/zip", "file"),
}

_GENERIC_MIME_TYPES = {"", "application/octet-stream", "binary/octet-stream"}
_KEY_PATTERN = re.compile(r"^[a-f0-9]{32}$")
_TEXT_MARKUP_PATTERN = re.compile(
    r"(?:<!--|<!DOCTYPE\b|<\?xml\b|</[A-Za-z][\w:.-]*\s*>|"
    r"</?(?:html|head|body|title|meta|link|style|script|noscript|iframe|"
    r"frame|frameset|svg|math|object|embed|applet|form|input|button|"
    r"textarea|select|option|img|image|audio|video|source|canvas|div|"
    r"span|p|a|base|template|foreignObject)\b|"
    r"<[A-Za-z][\w:.-]*(?:\s+[A-Za-z_:][\w:.-]*\s*=|\s+/\s*>|/\s*>))",
    re.IGNORECASE,
)
_TEXT_SCRIPT_PATTERN = re.compile(
    r"(?:\bjavascript\s*:|\b(?:eval|alert|prompt|confirm|Function)\s*\(|"
    r"\bdocument\s*\.\s*(?:write|writeln|cookie)\b|"
    r"\bwindow\s*\.\s*location\b|"
    r"^\s*(?:const|let|var)\s+[A-Za-z_$][\w$]*\s*=|"
    r"^\s*(?:async\s+)?function\s*[A-Za-z_$]*\s*\(|"
    r"^\s*(?:import|export)\s+(?:[\w*$,{]|default\b)|"
    r"^\s*console\s*\.\s*(?:log|warn|error)\s*\(|"
    r"=>)",
    re.IGNORECASE | re.MULTILINE,
)


def attachment_root() -> Path:
    configured = os.getenv("ATTACHMENT_STORAGE_DIR", "storage/attachments")
    return Path(configured).expanduser().resolve()


def attachment_path(storage_key: str) -> Path:
    if not _KEY_PATTERN.fullmatch(storage_key or ""):
        raise ValueError("Invalid attachment storage key")
    return attachment_root() / storage_key


def _validate_signature(extension: str, sample: bytes) -> None:
    signatures = {
        ".jpg": lambda data: data.startswith(b"\xff\xd8\xff"),
        ".jpeg": lambda data: data.startswith(b"\xff\xd8\xff"),
        ".png": lambda data: data.startswith(b"\x89PNG\r\n\x1a\n"),
        ".webp": lambda data: (
            len(data) >= 12 and data[:4] == b"RIFF" and data[8:12] == b"WEBP"
        ),
        ".pdf": lambda data: data.startswith(b"%PDF-"),
        ".doc": lambda data: data.startswith(b"\xd0\xcf\x11\xe0\xa1\xb1\x1a\xe1"),
        ".xls": lambda data: data.startswith(b"\xd0\xcf\x11\xe0\xa1\xb1\x1a\xe1"),
        ".docx": lambda data: data.startswith(b"PK\x03\x04"),
        ".xlsx": lambda data: data.startswith(b"PK\x03\x04"),
        ".zip": lambda data: data.startswith((b"PK\x03\x04", b"PK\x05\x06", b"PK\x07\x08")),
    }
    check = signatures.get(extension)
    if check and not check(sample):
        raise ValueError("File contents do not match the selected file type")

def _validate_text_file(path: Path) -> None:
    """Validate all TXT bytes and reject obvious markup or executable JS."""
    decoder = codecs.getincrementaldecoder("utf-8")("strict")
    pending = ""
    try:
        with path.open("rb") as source:
            while chunk := source.read(CHUNK_SIZE):
                text = decoder.decode(chunk)
                if any(
                    ord(char) < 32 and char not in "\t\n\r\f"
                    for char in text
                ):
                    raise ValueError("Text file contains binary or active content")
                scanned = pending + text
                if _TEXT_MARKUP_PATTERN.search(scanned):
                    raise ValueError("HTML or XML markup is not allowed in text files")
                if _TEXT_SCRIPT_PATTERN.search(scanned):
                    raise ValueError("JavaScript-like content is not allowed in text files")
                pending = scanned[-512:]
            tail = decoder.decode(b"", final=True)
    except UnicodeDecodeError as exc:
        raise ValueError("Text files must use UTF-8 encoding") from exc

    scanned = pending + tail
    if _TEXT_MARKUP_PATTERN.search(scanned):
        raise ValueError("HTML or XML markup is not allowed in text files")
    if _TEXT_SCRIPT_PATTERN.search(scanned):
        raise ValueError("JavaScript-like content is not allowed in text files")


async def save_upload(upload: UploadFile) -> tuple[str, str, str, int, str]:
    """Stream an upload to a generated private key and validate its contents."""
    filename = (upload.filename or "").replace("\\", "/").rsplit("/", 1)[-1]
    extension = Path(filename).suffix.lower()
    file_type = ALLOWED_TYPES.get(extension)
    if not filename or len(filename) > 255 or not file_type:
        raise ValueError("Unsupported attachment file type")

    mime_type, message_type = file_type
    supplied_type = (upload.content_type or "").split(";", 1)[0].strip().lower()
    if supplied_type not in _GENERIC_MIME_TYPES and supplied_type != mime_type:
        raise ValueError("Uploaded content type does not match the file extension")

    key = uuid.uuid4().hex
    root = attachment_root()
    root.mkdir(parents=True, exist_ok=True)
    target = attachment_path(key)
    temporary = root / f".{key}.tmp"
    size = 0
    sample = bytearray()

    try:
        with temporary.open("xb") as output:
            while True:
                chunk = await upload.read(CHUNK_SIZE)
                if not chunk:
                    break
                size += len(chunk)
                if size > MAX_ATTACHMENT_BYTES:
                    raise ValueError("Attachment exceeds the 25 MiB limit")
                if len(sample) < 8192:
                    sample.extend(chunk[: 8192 - len(sample)])
                output.write(chunk)

        if size == 0:
            raise ValueError("Attachment file is empty")
        _validate_signature(extension, bytes(sample))
        if extension == ".txt":
            _validate_text_file(temporary)
        temporary.replace(target)
        return key, filename, mime_type, size, message_type
    except Exception:
        temporary.unlink(missing_ok=True)
        target.unlink(missing_ok=True)
        raise


def remove_attachment(storage_key: str | None) -> None:
    if not storage_key:
        return
    try:
        attachment_path(storage_key).unlink(missing_ok=True)
    except (OSError, ValueError):
        # A failed cleanup should not undo a committed message deletion.
        pass
